export type OdhNormDataSummer = {
  id: number;
  technical_operation_name: string;
  technical_operation_id: number;
  standard_name: string;
  standard_id: number;
  unit: string;
  categorized_1: string;
  categorized_2: string;
  categorized_3: string;
  categorized_4: string;
  categorized_5: string;
  categorized_6a: string;
  categorized_6b: string;
  categorized_6c: string;
  categorized_7a: string;
  categorized_7b: string;
  uncategorized_highway: string;
  uncategorized_odhs_center: string;
  uncategorized_odhs_other: string;
};
