/*

export const STATUS_INSPECT_PGM_BASE_CONDITING = 'conducting';
export const STATUS_INSPECT_PGM_BASE_COMPLETED = 'completed';

export const STATUS_INSPECT_PGM_BASE = {
  STATUS_INSPECT_PGM_BASE_CONDITING,
  STATUS_INSPECT_PGM_BASE_COMPLETED,
};

export const STATUS_TITLE_BY_SLUG = {
  [STATUS_INSPECT_PGM_BASE_CONDITING]: 'Проводится',
  [STATUS_INSPECT_PGM_BASE_COMPLETED]: 'Завершена',
};

*/
