export const ENABLE_TRACKING_MODE = 'ENABLE_TRACKING_MODE';
export const DISABLE_TRACKING_MODE = 'DISABLE_TRACKING_MODE';
export const SHOW_PLATES = 'SHOW_PLATES';
export const HIDE_PLATES = 'HIDE_PLATES';
