export default {
  batteryRegistry: 'battery_registry',
  batteryBrand: 'battery_brand',
  batteryManufacturer: 'battery_manufacturer',
  tire: 'tire_registry',
  sparePart: 'spare_part_registry',
  sparePartGroup: 'spare_part_group',
  measureUnit: 'measure_unit',
  tireSize: 'tire_size',
  tireModel: 'tire_model',
  tireAvailibleCar: 'tire_available_car',
  actualBatteriesOnCar: 'actual_batteries_on_car',
  actualTiresOnCar: 'actual_tires_on_car',
  batteryAvailableCar: 'battery_available_car',
  techMaintOrder: 'tech_maintenance_order_registry',
  techMaintType: 'tech_maintenance_type',
  measureUnitRun: 'measure_unit_run',
  techInspection: 'tech_inspection_registry',
};
