export default [
  { key: 'equipment_fuel_end', float: 3 },
  { key: 'equipment_fuel_fact', float: 3 },
  { key: 'equipment_fuel_given', float: 3 },
  { key: 'equipment_fuel_start', float: 3 },
  { key: 'fuel_diff', float: 3 },
  { key: 'fuel_end', float: 3 },
  { key: 'fuel_fact', float: 3 },
  { key: 'fuel_given', float: 3 },
  { key: 'fuel_rate', float: 3 },
  { key: 'fuel_start', float: 3 },
  { key: 'motohours_diff', float: 3 },
  { key: 'motohours_end', float: 3 },
  { key: 'motohours_equip_diff', float: 3 },
  { key: 'motohours_equip_end', float: 3 },
  { key: 'motohours_equip_start', float: 3 },
  { key: 'motohours_start', float: 3 },
  { key: 'odometr_diff', float: 3 },
  { key: 'odometr_end', float: 3 },
  { key: 'odometr_start', float: 3 },
  { key: 'sensor_consumption', float: 3 },
  { key: 'consumption_diff', float: 3 },
  { key: 'track_length', float: 3 },
  { key: 'length_diff', float: 3 },
];
