export type EdcRequest = {
  additional_phone: string;
  address_comment: string;
  address_id: number;
  address_name: string;
  agreed_price: string;
  applicant_name: string;
  applicant_phone: string;
  bpm_operation: string;
  cancel_reason_id: number;
  cancel_reason_name: string;
  contractor_id: number;
  contractor_inn: string;
  contractor_name: string;
  create_date: string;
  create_date_ui: string;
  create_user_name: string;
  creator_fio: string;
  declarant_jur_id: number;
  declarant_name: string;
  defect_category_id: number;
  defect_id: number;
  defect_name: string;
  deffect_category_name: string;
  description: string;
  desired_date: string;
  desired_time_from: string;
  desired_time_to: string;
  district_name: string;
  emergency_id: number;
  emergency_name: string;
  eno: string;
  entrance_num: string;
  executor_id: number;
  feedback: string;
  flat: string;
  floor_num: string;
  grade: string;
  grade_id: string;
  house_address: string;
  id: number;
  intercom_code: string;
  is_card: boolean;
  latitude: string;
  longitude: string;
  main_phone: string;
  name: string;
  object_id: number;
  object_type: string;
  ods: string;
  okrug_name: string;
  pay_status_id: number;
  pay_status_name: string;
  payable_type_id: number;
  payable_type_name: string;
  phone: string;
  question: boolean;
  question_description: string;
  rating: string;
  rejection_reason_id: number;
  rejection_reason_name: string;
  request_id: number;
  request_number: string;
  request_send_at: string;
  rework: boolean;
  root_id: number;
  source: string;
  source_id: number;
  source_name: string;
  speciality: string;
  sso_id: number;
  start_date: string;
  status_id: number;
  status_name: string;
  substatus_id: number;
  uk_id: number;
  uk_inn: string;
  uk_name: string;
  work_type: string;

  mission_numbers: Array<number>;
  mission_numbers_text: string;
  duty_mission_numbers: Array<number>;
  duty_mission_numbers_text: string;

  peredano_v_ppoz: any;
  reason_name: string;
};

export type IStateEdcRequest = {
  EdcRequestList: Array<EdcRequest>;
};

export type EdcCancelReason = {
  code: any;
  edc_id: number;
  end_date: string | null;
  id: number;
  is_active: boolean;
  is_last: boolean;
  name: string;
  root_id: number;
  start_date: string;
};

export type EdcRejectionReason = {
  attribute: {
    name: string;
    attribute: any;
    reason_type_id: number;
  };
  create_date: string;
  deleted_at: any;
  edc_id: number;
  end_date: string;
  id: number;
  is_deleted: boolean;
  name: string;
};
