export type UserActionLog = {
  action: string;
  action_name: string;
  company_name: string;
  entity_id: number;
  fio: string;
  first_name: string;
  id: number;
  last_name: string;
  middle_name: string;
  okrug_name: string;
  remote_ip: string;
  structure_id: number;
  structure_name: string;
  action_at: string;
  user_id: number;
  user_login: string;
  content_type_name: string;
  repr: string;
};
