import { Country } from 'redux-main/reducers/modules/some_uniq/country/@types';
import { CarFuncTypes, CarCategory, EngineType, Car } from 'redux-main/reducers/modules/autobase/@types/autobase.h';
import { LoadingServiceGeneric } from './common';
import { TimeData } from './by_service/time';
import { ActualBatteriesOnCar } from 'redux-main/reducers/modules/autobase/actions_by_type/actual_batteries_on_car/@types';
import { ActualTiresOnCar } from 'redux-main/reducers/modules/autobase/actions_by_type/actual_tires_on_car/@types';
import { MeasureUnit } from 'redux-main/reducers/modules/some_uniq/measure_unit/@types';
import { CompanyStructureLinear } from 'redux-main/reducers/modules/company_structure/@types/company_structure.h';
import { Employee } from 'redux-main/reducers/modules/employee/@types/employee.h';
import { InspectAuditor } from './by_service/inspect_auditor';
import { EdcRequestComments } from 'components/new/utils/context/loading/@types/by_service/edc_request_comments';
import { EmployeeBindedToCar } from './by_service/employee_binded_to_car';
import { MedicalStatsAllowedDriver } from './by_service/medical_stats_allowed_drivers';
import { WorkMode } from 'redux-main/reducers/modules/some_uniq/work_mode/@types';
import { RefillType } from './by_service/refill_type';
import { FuelCard } from 'redux-main/reducers/modules/autobase/fuel_cards/@types/fuelcards.h';

export type CountryApi = LoadingServiceGeneric<'country', object, Array<Country>>;
export type TypesApi = LoadingServiceGeneric<'types', object, Array<CarFuncTypes>>;
export type AutobaseCarCategoryApi = LoadingServiceGeneric<'autobase/car_category', object, Array<CarCategory>>;
export type AutobaseEngineTypeApi = LoadingServiceGeneric<'autobase/engine_type', object, Array<EngineType>>;
export type TimeApi = LoadingServiceGeneric<'time', object, TimeData>;
export type AutobaseActualBatteriesOnCarApi = LoadingServiceGeneric<'autobase/actual_batteries_on_car', { car_id: Car['asuods_id']; }, ActualBatteriesOnCar>;
export type AutobaseActualTiresOnCarApi = LoadingServiceGeneric<'autobase/actual_tires_on_car', { car_id: Car['asuods_id']; }, ActualTiresOnCar>;
export type MeasureUnitApi = LoadingServiceGeneric<'measure_unit', object, Array<MeasureUnit>>;
export type CompanyStructureLinearApi = LoadingServiceGeneric<'company_structure', { linear: true; }, Array<CompanyStructureLinear>>;
export type EmployeeApi = LoadingServiceGeneric<'employee', object, Array<Employee>>;
export type CompanyStructureLinearForUserListApi = LoadingServiceGeneric<'company_structure', { linear: number; descendants_by_user: boolean; }, Array<CompanyStructureLinear>>;
export type CarActualApi = LoadingServiceGeneric<'car_actual', null, Array<Car>>;
export type InspectAuditorsApi = LoadingServiceGeneric<'inspect/auditors', object, Array<InspectAuditor>>;
export type EdcRequestCommentsApi = LoadingServiceGeneric<string, object, Array<EdcRequestComments>>;
export type EmployeeBindedToCarApi = LoadingServiceGeneric<'employee_binded_to_car', object, Array<EmployeeBindedToCar>>;
export type MedicalStatsAllowedDriverApi = LoadingServiceGeneric<'medical_stats/allowed_drivers', { company_id: number; date_from: string; date_to: string; type: 'before'; }, Array<MedicalStatsAllowedDriver>>;
export type WorkModeApi = LoadingServiceGeneric<'work_mode', null, Array<WorkMode>>;
export type RefillTypeApi = LoadingServiceGeneric<'refill_type', null, Array<RefillType>>;
export type FuelCardsApi = LoadingServiceGeneric<'fuel_cards', null, Array<FuelCard>>;
