export const STATUS_INSPECT_AUTOBASE_CONDITING = 'conducting';
export const STATUS_INSPECT_AUTOBASE_COMPLETED = 'completed';

export const STATUS_INSPECT_AUTOBASE = {
  STATUS_INSPECT_AUTOBASE_CONDITING,
  STATUS_INSPECT_AUTOBASE_COMPLETED,
};

export const STATUS_TITLE_BY_SLUG = {
  [STATUS_INSPECT_AUTOBASE_CONDITING]: 'Проводится',
  [STATUS_INSPECT_AUTOBASE_COMPLETED]: 'Завершена',
};
